# Site settings
title: Azure SQL with Spring Boot
author:
  name: Uday Kumar 
  email: banda.uday.kumar@gmail.com
description: "This site explains how to connect Azure SQL with Spring Boot Application"

# Build settings
#remote_theme: jekyll/minima
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
